name: Run Tests

on:
  push:
    paths-ignore:
      - "**/**.md"
      - "**/**.txt"
      - "**/**.dat"
      - "**/**.mca"
  pull_request:
    paths-ignore:
      - "**/**.md"
      - "**/**.txt"
      - "**/**.dat"
      - "**/**.mca"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run Tests
      run: cargo test